/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DepartureAlarm: typeof import('./components/DepartureAlarm.vue')['default']
    DepartureBoard: typeof import('./components/DepartureBoard.vue')['default']
    DepartureBoards: typeof import('./components/DepartureBoards.vue')['default']
    DepartureBoardTimetable: typeof import('./components/DepartureBoardTimetable.vue')['default']
    DepartureBoardTimetableDeparture: typeof import('./components/DepartureBoardTimetableDeparture.vue')['default']
    DigitalClock: typeof import('./components/DigitalClock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeatherDisplay: typeof import('./components/WeatherDisplay.vue')['default']
  }
}
