/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/DeparturesBoard copy.vue')['default']
    DepartureBoardTimetable: typeof import('./components/DepartureBoardTimetable.vue')['default']
    DeparturesBoard: typeof import('./components/DeparturesBoard.vue')['default']
    DeparturesBoardDeparture: typeof import('./components/DeparturesBoardDeparture.vue')['default']
    DeparturesBoards: typeof import('./components/DeparturesBoards.vue')['default']
    DeparturesBoardTimerableDeparture: typeof import('./components/DeparturesBoardTimerableDeparture.vue')['default']
    DeparturesBoardTimetable: typeof import('./components/DeparturesBoardTimetable.vue')['default']
    DeparturesBoardTimetableDeparture: typeof import('./components/DeparturesBoardTimetableDeparture.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
